name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
  contents: read
  pull-requests: read

jobs:
  call-reusable-demo:
    name: Call Reusable Workflow
    uses: ./.github/workflows/reusable.yml   # 👈 path to reusable WF
    with:
      logLevel: ${{ github.event.inputs.logLevel || 'warning' }}
      print_tags: ${{ github.event.inputs.print_tags || 'true' }}
      tags: ${{ github.event.inputs.tags || 0 }}
    secrets: inherit
