name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_call:
    inputs:
      logLevel:
        type: string
        required: true
        default: 'warning'
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: number
        default: 0
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.Explore-GitHub-Actions.outputs.output1 }}
jobs:
  Explore-GitHub-Actions:
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
    runs-on: ubuntu-latest
    steps:
      - id: Step1
        run: echo "🎉 The job was automatically triggered by a ${{ inputs.logLevel }} event."
      - run: echo "🐧 This job is now running on a ${{ inputs.print_tags }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "firstword=hello" >> $GITHUB_OUTPUT
  
